java implementation of vscode debug adapter data types
vscjavaci/eclipse.jdt.ls pull request #22
Opened 2017-07-26 08:23 UTC by testforstephen

2017-07-26 08:30 UTC, andxu approved these changes

2017-07-26 08:36 UTC, yaohaizh commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Events.java
> +        public String type;
public field?

2017-07-26 09:35 UTC, akaroml requested changes

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Events.java
> +    public static class DebugProtocolCallbacks {
Remove unused one.

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Results.java
> +    public static class DebugResult {
Seems this is not necessary. DispatcherReponse/DispatcherEvent can be used directly.

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Types.java
> +        public boolean supportsStepBack;
We won't support this..

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Types.java
> +        public List<ExceptionBreakpointFilter> exceptionBreakpointFilters;
Not supported for now. Remote this line.

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Types.java
> +        public boolean supportsDelayedStackTraceLoading;
Not supported.

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Types.java
> +        public boolean supportsConditionalBreakpoints;
Not supported.

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Types.java
> +        public boolean supportsHitConditionalBreakpoints;
Not supported.

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Types.java
> +        public boolean supportsFunctionBreakpoints;
Not supported.

2017-07-26 09:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Types.java
> +    public static class Capabilities {
Add supportTerminateDebuggee.

2017-07-27 01:29 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Events.java
> +        public String type;
yes, the field should be accessed by gson serialization and de-serialization.

2017-07-27 10:32 UTC, akaroml approved these changes
Perfect. Thank you!
Please **Squash and merge**

2017-07-28 01:38 UTC, merged