add ILanguageServerInfoProvider interface
vscjavaci/eclipse.jdt.ls pull request #25
Opened 2017-08-01 08:15 UTC by ansyral

@andxu @testforstephen @yaohaizh @akaroml

2017-08-01 08:17 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ILanguageServerInfoProvider.java
> +    String[] getClassPath(String mainClassFullyQualifiedName, String projectName);
why we need mainClassFullyQualifiedName/projectName to getClassPath

2017-08-01 08:31 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ILanguageServerInfoProvider.java
> +    String getFullyQualifiedName(String sourceFilePath, int line, int column);
we don't support column breakpoint. so here just need two parameters `sourceFilePath` and `line`

2017-08-01 08:32 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ILanguageServerInfoProvider.java
> +    String getFullyQualifiedName(String sourceFilePath, int line, int column);
please also add batch get interface String[] getFullyQualifiedName(String sourceFilePath, int[] lines)

2017-08-01 08:48 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ILanguageServerInfoProvider.java
> +    String getURI(String fullyQualifiedName, String projectName);
Actually `getSourceFilePath` and `getURI` do the same thing. Just need one API `getURI`.

2017-08-01 08:53 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ILanguageServerInfoProvider.java
> +    String getFullyQualifiedName(String sourceFilePath, int line, int column);
String[] getFullyQualifiedName(String sourceFilePath, int[] lines) is enough.

2017-08-01 12:14 UTC, ansyral commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ILanguageServerInfoProvider.java
> +    String getFullyQualifiedName(String sourceFilePath, int line, int column);
How about the caller to do the batch operation as each line only resolve one fullyqualifiedname?

2017-08-01 12:22 UTC, ansyral commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ILanguageServerInfoProvider.java
> +    String getFullyQualifiedName(String sourceFilePath, int line, int column);
the method isn't only for getting breakpoint?

2017-08-02 06:08 UTC, akaroml requested changes

2017-08-02 06:08 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/IVirtualMachineManagerProvider.java
> +public interface IVirtualMachineManagerProvider {
What's this for?

2017-08-02 06:08 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ISourceLookUpProvider.java
> +    void initializeContext(Map<String, Object> props);
If all provider shares the same initialize routine, make it another interface and let others extend it.

2017-08-02 06:37 UTC, ansyral commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/IVirtualMachineManagerProvider.java
> +public interface IVirtualMachineManagerProvider {
current implementation is that debugger used the same virtualmachinemanager as language server, which is `org.eclipse.jdi.Bootstrap.virtualMachineManager`, we can encapsulate this.

2017-08-02 06:41 UTC, ansyral commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ISourceLookUpProvider.java
> +    void initializeContext(Map<String, Object> props);
cool

2017-08-02 07:31 UTC, akaroml requested changes

2017-08-02 07:31 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/IHasContext.java
> +public interface IHasContext {
Not quite sure about the naming. Is the context used by providers? If that's the case, then it's a common behavior across all providers. And a common IProvider is recommended.

2017-08-02 10:11 UTC, akaroml approved these changes

2017-08-02 10:20 UTC, akaroml commented
Please fix the build error.

2017-08-03 03:00 UTC, merged