Support restart and stop
vscjavaci/eclipse.jdt.ls pull request #29
Opened 2017-08-03 08:08 UTC by testforstephen

2017-08-03 10:14 UTC, akaroml requested changes

2017-08-03 10:14 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/DebugException.java
> +    private static final long serialVersionUID = 1L;
What's this for?

2017-08-03 10:14 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/DebugException.java
> +    public DebugException() {
Maybe we can remove this. An exception without any description or cause should not be used.

2017-08-03 10:14 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            return new Responses.ErrorResponseBody(new Types.Message(3001, "Cannot launch debuggee vm: " + e.getMessage(), null));
Still, don't understand the code 3001. Why do we need to specify this number?

2017-08-03 10:14 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            return new Responses.ErrorResponseBody(new Types.Message(3001, "Cannot restart debuggee vm: " + e.getMessage(), null));
Same here.

2017-08-03 10:14 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
>          } else if (event instanceof VMDeathEvent || event instanceof VMDisconnectEvent) {
VMDeathEvent and VMDisconnectEvent have different meanings and indicate different stages of termination. Please handle them in different code branch.

2017-08-03 10:14 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Events.java
> +        public ContinuedEvent(long id) {
name the parameter threadId

2017-08-03 10:14 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Events.java
> +        public ContinuedEvent(long id, boolean allThreadsContinued) {
threadId

2017-08-04 01:54 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/DebugException.java
> +    private static final long serialVersionUID = 1L;
DebugException extends Serializable, and Serializable should declare a field `serialVersionUID`.
https://stackoverflow.com/questions/285793/what-is-a-serialversionuid-and-why-should-i-use-it

2017-08-04 01:56 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/DebugException.java
> +    public DebugException() {
DebugException extends Exception. And from javadoc of Exception's default constructor `java.lang.Exception.Exception()`, it said `
Constructs a new exception with null as its detail message. The cause is not initialized, and may subsequently be initialized by a call to initCause.
`

2017-08-04 02:26 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            return new Responses.ErrorResponseBody(new Types.Message(3001, "Cannot launch debuggee vm: " + e.getMessage(), null));
Accord to debugProtocol, in ErrorResponse body, we could set an optional structure Message. And the Message has a required id field. The code 3001 just reference to OpenDebugAD7 error code.

2017-08-04 02:26 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            return new Responses.ErrorResponseBody(new Types.Message(3001, "Cannot launch debuggee vm: " + e.getMessage(), null));
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts

2017-08-04 08:46 UTC, akaroml approved these changes
Nice work. Thanks.

2017-08-04 08:47 UTC, merged