Support pause and resume
vscjavaci/eclipse.jdt.ls pull request #33
Opened 2017-08-07 01:43 UTC by testforstephen

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

2017-08-07 06:55 UTC, ansyral commented
:shipit:

2017-08-07 09:58 UTC, akaroml requested changes

2017-08-07 09:58 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            debugEvent.shouldResume &= false;
Why do we use &= operator? EventHub actually does so.
I think the assignment is enough here.

2017-08-07 09:58 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
>              debugEvent.shouldResume &= false;
Same here. The assignment operator is enough.

2017-08-08 01:13 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            debugEvent.shouldResume &= false;
agree.

2017-08-08 03:36 UTC, akaroml approved these changes
Nice job! Thanks.

2017-08-08 04:08 UTC, merged