Support hitCount breakpoint
vscjavaci/eclipse.jdt.ls pull request #35
Opened 2017-08-08 06:21 UTC by testforstephen

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

2017-08-08 07:07 UTC, akaroml requested changes

2017-08-08 07:07 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/BreakpointManager.java
> +        if (AdapterUtils.isWindows()) {
Windows is not sensitive to cases in file paths. Why do we still have to convert everything to lower case?

2017-08-08 09:43 UTC, akaroml requested changes
Please remove the logic to handle OS specific path issues. These should be handled by VSCode. At the same time, we can use URI as breakpoint key to resolve the issue at our side.

2017-08-10 08:32 UTC, akaroml requested changes

2017-08-10 08:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +    private boolean debuggerPathsAreURI = true;
debuggerPathsAreURI => debuggerPathsAreUri

2017-08-10 08:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            String drive = clientPath.substring(0, 2);
This does not look good. Please consider org.apache.commons.io.FilenameUtils.getPrefix or use regular expression.

2017-08-10 08:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
>      private boolean clientPathsAreURI = false;
clientPathsAreURI => clientPathsAreUri

2017-08-10 08:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            String drive = clientPath.substring(0, 2);
We use URIs internally. So the drive letters of different cases won't result in duplicated breakpoints. Do we still need to keep normalizing the drive letter?

2017-08-10 08:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            int dollar = fullyQualifiedName.indexOf('$');
Please use a regular expression for matching strings.

2017-08-10 08:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JdtSourceLookUpProvider.java
> +                    Logger.logException("Add breakpoint exception", e);
Why should the getFullyQualifiedName utility function throw breakpoint exception?

2017-08-11 02:07 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JdtSourceLookUpProvider.java
> +                    Logger.logException("Add breakpoint exception", e);
`IJavaElement javaElement = typeRoot.getElementAt(offset);` may throw JavaModelException. Current policy is to eat the exception. That may be not the correct handing policy. I'll choose to throw it out and let dispatcher send an error response to vscode.

2017-08-11 02:08 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            int dollar = fullyQualifiedName.indexOf('$');
agree.

2017-08-11 02:17 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +    private boolean debuggerPathsAreURI = true;
fixed.

2017-08-11 02:17 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
>      private boolean clientPathsAreURI = false;
fixed

2017-08-11 02:17 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            String drive = clientPath.substring(0, 2);
fixed.

2017-08-11 03:13 UTC, akaroml requested changes

2017-08-11 03:13 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +            String drivePrefix = FilenameUtils.getPrefix(clientPath);
Here's the case of one day VSCode supports URI and then pass the path in URI format. e.g. file:///c:\abc.java.
Then the prefix you get is actually file:/// but not c:\.
That's why I suggest a second check on the prefix to use regex to match for drive info.

2017-08-11 03:17 UTC, akaroml approved these changes

2017-08-11 03:19 UTC, merged