Move Varaible logic out of DebugAdatper
vscjavaci/eclipse.jdt.ls pull request #37
Opened 2017-08-09 02:58 UTC by andxu

2017-08-09 03:12 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/VariableDebugAdapter.java
> +        return new Responses.StackTraceResponseBody(result, result.size());
The second argument should be total frame count available.

2017-08-09 03:29 UTC, testforstephen submitted a review, later dismissed

2017-08-09 04:14 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/VariableDebugAdapter.java
> +        return new Responses.StackTraceResponseBody(result, result.size());
Done

2017-08-09 05:12 UTC, testforstephen submitted a review, later dismissed

2017-08-11 07:57 UTC, ansyral commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/VariableDebugAdapter.java
> +        this.parent = debugAdapter;
>parent [](start = 13, length = 6)

Question, what's the relationship between VariableDebugAdapter and DebugAdapter? the naming makes me think about inheritance and actually it isn't

2017-08-11 08:03 UTC, ansyral commented
:shipit:

2017-08-14 01:13 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/VariableDebugAdapter.java
> +        this.parent = debugAdapter;
DebugAdapter is not inheritable, will refactor it latter.

2017-08-14 05:32 UTC, akaroml requested changes

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/internal/EventHub.java
> +     * Start the vm.
"Starts retrieving events from the event queue of the specified virtual machine."

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/IdCollection.java
> +        this.nextId.set(this.startId);
Is there a style check rule for this (empty statement)?

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +        if (defaultOptions == null) {
Suggest raising exception when defaultOptions.size() != valueFormatterMap.size() + typeFormatterMap.size();
This indicates duplication.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +        defaultOptions = null;
Suggest not using a cache. We don't need to maintain the status when a cache is not used.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +        defaultOptions = null;
Same as above.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +    public boolean isIncludeStatic() {
This should be an option instead of a member function of the provider.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +    public void setIncludeStatic(boolean includeStatic) {
Please also make it an option.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +        for (Map.Entry<String, Object> entry : formatter.getDefaultOptions().entrySet()) {
Let's generate the default options each time the function is called without using cache to simply the problem first.
Adding cache should be a separate change list.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +    private static IFormatter getFormatter(Map<? extends IFormatter, Integer> formatterMap, Type type,
So good to make the function static! Good move!

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +        List<? extends IFormatter> formatterList =
Thumb up for leveraging stream API!

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/IVariableProvider.java
> +    IValueFormatter getValueFormatter(Type type, Map<String, Object> options);
Do we really need this?
I think the provider already formats the value/type for the caller instead of letting the caller get the formatter.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Variable.java
> +    public Type getDeclaringType() {
The logic is so simple, do we still need it?

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/SetValueFunction.java
> +interface SetValueFunction {
Where is this used?

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/StackFrameScope.java
> +public class StackFrameScope {
I don't see it used anywhere. Please include in other change lists that really use it.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ThreadObjectReference.java
> +public class ThreadObjectReference {
I don't see it used anywhere. Please include in other change lists that really use it.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +    public IValueFormatter getValueFormatter(Type type, Map<String, Object> options) {
Why do we need to expose formatter to callers? I think the variable provider already format the value/type.

2017-08-14 05:32 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/RecyclableObjectPool.java
> +public class RecyclableObjectPool<O, V> {
Please include it in the change list that really uses it.

2017-08-14 05:47 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +    public IValueFormatter getValueFormatter(Type type, Map<String, Object> options) {
On setValue, when we have a type and a String value, we need the related formatter to restore the JDI value for calling setValue in JDI.

2017-08-14 06:01 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +        defaultOptions = null;
Done

2017-08-14 06:01 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DefaultVariableProvider.java
> +        if (defaultOptions == null) {
Done

2017-08-14 06:33 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/IdCollection.java
> +        this.nextId.set(this.startId);
done

2017-08-14 06:34 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/RecyclableObjectPool.java
> +public class RecyclableObjectPool<O, V> {
It is used in VariableRequestHandler.

2017-08-14 06:34 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Variable.java
> +    public Type getDeclaringType() {
a lot of places need to get the declare type of this variable, create an getter method to avoid duplicate code.

2017-08-14 06:41 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Variable.java
> +    public Type getDeclaringType() {
when name conflicts, the declare type will be the differentiator.

2017-08-14 06:45 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/SetValueFunction.java
> +interface SetValueFunction {
It is used in variable handler,I have removed now in this PR.

2017-08-14 06:47 UTC, akaroml approved these changes

2017-08-14 06:47 UTC, akaroml commented on google_checks.xml
> +        <module name="EmptyStatement"/>
Nice!

2017-08-14 06:56 UTC, merged