Print debuggee console
vscjavaci/eclipse.jdt.ls pull request #38
Opened 2017-08-11 05:29 UTC by testforstephen

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

2017-08-11 05:36 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Events.java
> -        public HashMap<String, Object> data;
using Map instead

2017-08-11 05:39 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ProcessConsole.java
> +            public void run() {
duplicate code with stderrThread

2017-08-11 06:34 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/Events.java
> -        public HashMap<String, Object> data;
The code is removed.

2017-08-11 06:34 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ProcessConsole.java
> +            public void run() {
fixed.

2017-08-11 07:45 UTC, ansyral commented
:shipit:

2017-08-14 05:52 UTC, akaroml requested changes

2017-08-14 05:52 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ProcessConsole.java
> +                subject.onComplete();
onError when exception is thrown.

2017-08-14 06:02 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/ProcessConsole.java
> +                subject.onComplete();
fixed.

2017-08-14 07:27 UTC, akaroml approved these changes
Thanks.

2017-08-14 07:57 UTC, merged