Support attach debug & remove restartRequest support
vscjavaci/eclipse.jdt.ls pull request #42
Opened 2017-08-15 04:16 UTC by testforstephen

- See PR8 (https://github.com/vscjavaci/vscode-java/pull/8) on the vscode-java extension side.
- Support attach debug.
- Remove restartRequest support
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

2017-08-15 05:04 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +    private boolean isAttaching = false;
attachingMode is better?

2017-08-15 05:05 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +        this.cwd = arguments.cwd;
dup code with launch

2017-08-15 05:06 UTC, andxu commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +            singletonServer = new SingletonDebugServer();
InternalDebugServer?

2017-08-15 06:35 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +        this.cwd = arguments.cwd;
will fix duplicate code in the new adapter handler.

2017-08-15 06:35 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +            singletonServer = new SingletonDebugServer();
fixed.

2017-08-15 06:35 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +    private boolean isAttaching = false;
fixed.

2017-08-15 10:22 UTC, akaroml requested changes

2017-08-15 10:22 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
>  public class JavaDebugServer implements IDebugServer {
Why not make the JavaDebugServer itself a singleton instead of hosting an internal class?

2017-08-15 10:22 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +    private static synchronized void createIfNotExist() {
Usually, we use getInstance() as the entry for getting the singleton.

2017-08-15 10:22 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +            new Thread(() -> {
Who will manage this thread?

2017-08-16 02:57 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
>  public class JavaDebugServer implements IDebugServer {
JavaDebugServer extends the eclipse extension point, and eclipse will new a instance using the default constructor every time, so use the internal class to implement singleton pattern. However, i found another usage about extension point by using Extension Factory, see my new change set. It implements singleton pattern in JavaDebugServer directly, and let eclipse invoke a factory (IExecutableExtensionFactory#create()) to create extension instance.

2017-08-16 02:57 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +    private static synchronized void createIfNotExist() {
fixed.

2017-08-16 03:02 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +            new Thread(() -> {
The thread will have the same life cycle as the socket connection. And keep alive when the Socket connection is alive. Die when socket connection is closed. So the thread is managed by socket connection potentially.

2017-08-16 03:35 UTC, akaroml requested changes

2017-08-16 03:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +    private boolean attachingMode = false;
One minor thing: attachingMode => isAttached

2017-08-16 03:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +    public synchronized static IDebugServer getInstance() {
Nice

2017-08-16 03:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +        new Thread(() -> {
The new thread is left unmanaged and unreferenced. I think this function should return the new thread. And the thread should be stopped/interrupted in stop().

2017-08-16 03:35 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +            Logger.logException("Failed to create Internal Debug Server", e);
There is no inter debug server now. The message should be "Failed to create the debug server."

2017-08-16 05:18 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> +    private boolean attachingMode = false;
fixed.

2017-08-16 05:18 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +            Logger.logException("Failed to create Internal Debug Server", e);
fixed.

2017-08-16 05:19 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
> +        new Thread(() -> {
fixed. will use Java Thread Pool to manage the newly created thread. and stop all threads when invoking stop().

2017-08-16 05:47 UTC, ansyral commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> -
Question, we don't support restart any more?

2017-08-16 06:34 UTC, testforstephen commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/DebugAdapter.java
> -
Not really. it just means we don't support restart request in debug session, but support the old restart policy (disconnect first and relaunch).

2017-08-17 02:57 UTC, akaroml commented on org.eclipse.jdt.ls.debug/src/org/eclipse/jdt/ls/debug/adapter/jdt/JavaDebugServer.java
>  public class JavaDebugServer implements IDebugServer {
Perfect. The new code is simpler and easier to understand.

2017-08-17 02:58 UTC, akaroml approved these changes
Good job. Thanks!

2017-08-17 03:00 UTC, merged